<?
require_once('library.inc');
?>
<html><head><title><?php print $SITENAME;?></title></head><body>
<script>function LogoJump(){window.location="/";}</script>
<link href="master.css" rel="stylesheet" type="text/css"/>
<div class="headerlogo" onClick="LogoJump();">YNA</div>
<div class="headerAdBannerSpace"></div>
<div class="menubox"><?php  include('includes/menubox.php'); ?></div>
<br clear="all">
